## Nhap ma tran

In [2]:
import numpy as np

A = np.array([
    [1,2,3,2],
    [2,3,5,7],
    [4,5,2,1],
    [9,8,2,1]
])

In [3]:
A

array([[1, 2, 3, 2],
       [2, 3, 5, 7],
       [4, 5, 2, 1],
       [9, 8, 2, 1]])

In [8]:
from scipy.fftpack import fft, dct, idct, ifft

A_dct = dct(A, type = 2, norm='ortho')

In [10]:
A_dct

array([[ 4.        , -0.92387953, -1.        ,  0.38268343],
       [ 8.5       , -3.80760351,  0.5       , -0.04642729],
       [ 6.        ,  2.7716386 , -1.        , -1.1480503 ],
       [10.        ,  6.84984016,  0.        , -1.75490449]])

In [9]:
A_idct = idct(A_dct, type = 2, norm='ortho')
A_idct

array([[1., 2., 3., 2.],
       [2., 3., 5., 7.],
       [4., 5., 2., 1.],
       [9., 8., 2., 1.]])

In [37]:
A_fft = np.fft.fft2(A, norm = 'ortho')

In [38]:
A_fft

array([[14.25+0.j  ,  1.  -1.75j, -0.25+0.j  ,  1.  +1.75j],
       [-1.  +0.75j,  1.75+3.5j ,  0.  +1.25j, -3.75+1.5j ],
       [-4.25+0.j  , -1.  -0.25j,  0.25+0.j  , -1.  +0.25j],
       [-1.  -0.75j, -3.75-1.5j ,  0.  -1.25j,  1.75-3.5j ]])

In [40]:
A_ifft = np.fft.ifft2(A_fft, norm = 'ortho')

In [41]:
A_ifft

array([[1.+0.j, 2.+0.j, 3.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j, 5.+0.j, 7.+0.j],
       [4.+0.j, 5.+0.j, 2.+0.j, 1.+0.j],
       [9.+0.j, 8.+0.j, 2.+0.j, 1.+0.j]])

In [11]:
A_10 = A+10

In [13]:
A_10

array([[11, 12, 13, 12],
       [12, 13, 15, 17],
       [14, 15, 12, 11],
       [19, 18, 12, 11]])

In [14]:
print(A**3)

[[  1   8  27   8]
 [  8  27 125 343]
 [ 64 125   8   1]
 [729 512   8   1]]


In [17]:
C = np.sum(A<5)

In [18]:
C

np.int64(11)

In [21]:
import scipy.linalg as la

results = la.eig(A)
print('vector rieng',results[1])
print('gia tri rieng: ',results[0])

vector rieng [[ 0.27763309+0.j          0.14169871+0.j         -0.50387842+0.06004228j
  -0.50387842-0.06004228j]
 [ 0.61573504+0.j          0.6218308 +0.j          0.58402738+0.j
   0.58402738-0.j        ]
 [ 0.39480374+0.j         -0.32993748+0.j         -0.28988502-0.42111601j
  -0.28988502+0.42111601j]
 [ 0.62283244+0.j         -0.69598074+0.j          0.09419919+0.3621712j
   0.09419919-0.3621712j ]]
gia tri rieng:  [14.18843576+0.j         -7.03191738+0.j         -0.07825919+0.94122801j
 -0.07825919-0.94122801j]


#### tinh sum, mean, std, max, min theo hang, theo cot, toan ma tran

Toàn bảng

In [22]:
print('sum: ', np.sum(A))
print('mean: ', np.mean(A))
print('max: ', np.max(A))
print('min: ', np.min(A))

sum:  57
mean:  3.5625
max:  9
min:  1


Theo cột

In [23]:
print('sum: ', np.sum(A, axis = 0))
print('mean: ', np.mean(A, axis = 0))
print('max: ', np.max(A, axis = 0))
print('min: ', np.min(A, axis = 0))

sum:  [16 18 12 11]
mean:  [4.   4.5  3.   2.75]
max:  [9 8 5 7]
min:  [1 2 2 1]


Theo hàng


In [24]:
print('sum: ', np.sum(A, axis = 1))
print('mean: ', np.mean(A, axis = 1))
print('max: ', np.max(A, axis = 1))
print('min: ', np.min(A, axis = 1))

sum:  [ 8 17 12 20]
mean:  [2.   4.25 3.   5.  ]
max:  [3 7 5 9]
min:  [1 2 1 1]


## Tinh tich phan

In [30]:
from scipy import integrate
f = lambda x: x**2 + np.sin(x)
result = integrate.quad(f, 0, np.pi)
print(f"Ket qua tich phan: {result}")

Ket qua tich phan: (12.33542556009994, 1.3695073475372622e-13)


### Tính đạo hàm

In [31]:
import sympy
x = sympy.Symbol('x')
y = x**4 - 5*x**2 +20*sympy.cos(x)
y1 = y.diff(x)
print(y1)
for i in range (-10, 10):
    print(y1.subs(x,i).evalf())

4*x**3 - 10*x - 20*sin(x)
-3910.88042221779
-2817.75763029516
-1948.21283506753
-1288.86026802562
-809.588309963979
-469.178485493263
-231.136049906159
-75.1775998388026
6.18594853651363
22.8294196961579
0
-22.8294196961579
-6.18594853651363
75.1775998388026
231.136049906159
469.178485493263
809.588309963979
1288.86026802562
1948.21283506753
2817.75763029516


### Tính lim

In [29]:
import sympy
x = sympy.symbols('x')
y = (3*x**2 + 2*x -5)/(x**3+7*x**2+1)
result = sympy.limit(y, x, np.inf)
result

0

### Gia tri lon nhat, be nhat cua ham so tren doan

In [27]:
from scipy.optimize import fminbound
import math

def f(x): return np.cos(x)**2 + x**3 - 5*x
min_loc = fminbound(f, -2, 3)
print(min_loc)

1.3459444808875867


## Giai he phương trình

In [26]:
a = np.array([[1,2,1],[1,3,2],[1,1,-1]], dtype=float)
b = np.array([[6],[3],[4]], dtype=float)
sol = np.linalg.solve(a,b)
x, y, z = sol
print(f"Nghiem cua he phuong trinh {x} ,{y} ,{z}")

Nghiem cua he phuong trinh [17.] ,[-8.] ,[5.]
